export const COLORS = {
  WHITE: 'WHITE',
  BLACK: 'BLACK',
  ORRANGE: 'ORRANGE',
  ORRANGE_GRADIENT: 'ORRANGE-GRADIENT',
  YELLOW: 'YELLOW',
  GREEN: 'GREEN',
  RED: 'RED',
  GRAY_LIGHT: 'GRAY-LIGHT',
  GRAY_4: 'GRAY_4',
}

export const COLORS_VALUES = {
  [COLORS.WHITE]: '#ffffff',
  [COLORS.BLACK]: '#000000',
  [COLORS.ORRANGE]: '#FE9013',
  [COLORS.YELLOW]: '#ffee2e',
  [COLORS.GREEN]: '#4B9200',
  [COLORS.RED]: '#D31414',
  [COLORS.GRAY_LIGHT]: '#F1F3F2',
  [COLORS.GRAY_4]: '#BDBDBD',
}
