export const cardAnimals = [
  {
    id: 0,
    title: 'Giant Pandas',
    habitat: 'Native to Southwest China',
    description: '',
    imageSrc: `/images/sectionPets/pandas.jpg`,
    foodType: 'vegetables',
  },
  {
    id: 1,
    title: 'Eagles',
    habitat: 'Native to South America',
    description: '',
    imageSrc: `/images/sectionPets/eagles.jpg`,
    foodType: 'meet',
  },
  {
    id: 2,
    title: 'Gorillas',
    habitat: 'Native to Congo',
    description: '',
    imageSrc: `/images/sectionPets/gorillas.jpg`,
    foodType: 'vegetables',
  },
  {
    id: 3,
    title: 'Two-toed Sloth',
    habitat: 'Mesoamerica, South America',
    description: '',
    imageSrc: `/images/sectionPets/two-toed-sloth.jpg`,
    foodType: 'vegetables',
  },
  {
    id: 4,
    title: 'Cheetahs',
    habitat: 'Native to Africa',
    description: '',
    imageSrc: `/images/sectionPets/cheetahs.jpg`,
    foodType: 'meet',
  },
  {
    id: 5,
    title: 'Penguins',
    habitat: 'Native to Antarctica',
    description: '',
    imageSrc: `/images/sectionPets/penguins.jpg`,
    foodType: 'meet',
  },
  {
    id: 6,
    title: 'Alligators',
    habitat: 'Native to Southeastern U. S.',
    description: '',
    imageSrc: `/images/sectionPets/alligators.jpg`,
    foodType: 'meet'
  },
]
